/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository — the event
 * vocabulary this build understands. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`): such a log was likely written by a newer harness, and
 * silently skipping a required event would reconstruct a wrong session.
 * Plugins may register additional log-only event types at boot; those
 * registrations extend this set without coupling the core to each plugin.
 */
const knownSessionEventTypes = new Set([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/chunk',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'feedback/record',
  'goal/change',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/descriptor',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/code-dispatch',
  'tool/code-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
])

/** Runtime validation hook for a durable event contributed by a loaded plugin. */
export interface SessionEventRegistrationOptions {
  /** Validate and normalize the persisted payload before replay. */
  readonly decode?: (data: unknown) => unknown
  /** Keep this durable decoder available after its plugin is unloaded. */
  readonly retainOnDispose?: boolean
}

/** Register a durable event type contributed by a loaded plugin. */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = knownSessionEventTypes

const pluginEventReferences = new Map<string, number>()
const pluginEventDecoders = new Map<string, (data: unknown) => unknown>()
const retainedPluginEvents = new Set<string>()

export function registerKnownSessionEventType(type: string, options?: SessionEventRegistrationOptions): () => void {
  if (!/^[a-z0-9][a-z0-9._-]*\/[a-z0-9][a-z0-9._-]*$/i.test(type)) throw new Error('session event type must use namespace/name syntax')
  if (knownSessionEventTypes.has(type) && !pluginEventReferences.has(type)) {
    // Built-in events need no registration. A retained plugin event already
    // has a process-lifetime decoder; validate a competing decoder instead of
    // silently accepting a different replay contract.
    const existing = pluginEventDecoders.get(type)
    if (retainedPluginEvents.has(type) && options?.decode !== undefined && existing !== undefined && existing !== options.decode) {
      throw new Error(`session event type ${type} already has a different decoder`)
    }
    if (retainedPluginEvents.has(type) && options?.decode !== undefined && existing === undefined) {
      pluginEventDecoders.set(type, options.decode)
    }
    return () => undefined
  }
  if (options?.decode !== undefined) {
    const existing = pluginEventDecoders.get(type)
    if (existing !== undefined && existing !== options.decode) throw new Error(`session event type ${type} already has a different decoder`)
    pluginEventDecoders.set(type, options.decode)
  }
  if (options?.retainOnDispose === true) retainedPluginEvents.add(type)
  pluginEventReferences.set(type, (pluginEventReferences.get(type) ?? 0) + 1)
  knownSessionEventTypes.add(type)
  let disposed = false
  return () => {
    if (disposed) return
    disposed = true
    const remaining = (pluginEventReferences.get(type) ?? 1) - 1
    if (remaining <= 0) {
      pluginEventReferences.delete(type)
      if (!retainedPluginEvents.has(type)) {
        pluginEventDecoders.delete(type)
        knownSessionEventTypes.delete(type)
      }
    }
    else pluginEventReferences.set(type, remaining)
  }
}

/** Decode a registered plugin payload; built-in events pass through unchanged. */
export function decodeRegisteredSessionEventData(type: string, data: unknown): unknown {
  return pluginEventDecoders.get(type)?.(data) ?? data
}
